// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari", 
  options: {
    // Hide the finicky icon from the top bar. Default: false
    hideIcon: false, 
    // Check for update on startup. Default: true
    checkForUpdate: true,
    // Override the internal list of url shortener services 
    urlShorteners: ["t.co", "i.datachef.co"]
  },

  rewrite: [
    {
      match: ({ url }) => url.protocol === "http",
    url: {
      protocol: "https"
    }
  },

  {    
    match: "amazon.com*",
    url: {
      host: "smile.amazon.com"
    }
  }
],

handlers: [
  {
    match: "open.spotify.com*",
    browser: "Spotify"
  },
  {
    match: [
      "zoom.us*", // match zoom.us urls
      finicky.matchDomains(/.*\.zoom.us/) // use helper function to match on domain only
    ],
    browser: "us.zoom.xos"
  },
  {
    // Open Chrome extensions in Google Chrome
    match: "https://chrome.google.com/webstore/*",
    browser: "Google Chrome"
  },
  {
    // Open LinkedIn and Sales Navigator in Google Chrome
    match: "https://*.LinkedIn.com/*",
    browser: "Google Chrome"
  }
]   

}
