// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari", 
  options: {
    // Hide the finicky icon from the top bar. Default: false
    hideIcon: false, 
    // Check for update on startup. Default: true
    checkForUpdate: true,
    // Override the internal list of url shortener services 
    urlShorteners: ["t.co", "i.datachef.co"]
  },

  rewrite: [
    {
      match: ({ url }) => url.protocol === "http",
    url: {
      protocol: "https"
    }
  },

  {    
    match: "amazon.com*",
    url: {
      host: "smile.amazon.com"
    }
  },

  {    
    match: "amazon.de*",
    url: {
      host: "smile.amazon.de"
    }
  },

  {
    // https://github.com/johnste/finicky/issues/96
    // Redirect all https://slack.com/app_redirect?team=team=apegroup&channel=random 
    // to slack://channel?team=apegroup&id=random
    match: ({ url }) => url.host.includes("slack.com") && url.pathname.includes("app_redirect"),
    url({ url }) {
      const team = url.search.split('&').filter(part => part.startsWith('team'));
      var channel = "" + url.search.split('&').filter(part => part.startsWith('channel'));
      var id = channel.replace("channel", "id");

      return {
          protocol: "slack",
          username: "",
          password: "",
          host: "channel",
          port: null,
          pathname: "",
          search : team + '&' + id,
          hash: ""
      }
      
    }
  }
],

handlers: [
  {
    match: "open.spotify.com*",
    browser: "Spotify"
  },
  {
    match: [
      "zoom.us*", // match zoom.us urls
      finicky.matchDomains(/.*\.zoom.us/) // use helper function to match on domain only
    ],
    browser: "us.zoom.xos"
  },
  {
    // Open Chrome extensions in Google Chrome
    match: "https://chrome.google.com/webstore/*",
    browser: "Google Chrome"
  },
  {
    // Open LinkedIn and Sales Navigator in Google Chrome
    match: "https://*.Linkedin.com/*",
    browser: "Google Chrome"
  }
]   

}
